name: DEPLOY TO SERVER
on: 
  push:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn
      - name: Build and Deploy
        run: yarn build