name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        use: actions/checkout@v2
      - name: User Node V.16x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x