name: Deploy
on: 
  push:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn
      - name: Build and Deploy
        run: yarn build
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: 13.213.67.241
          username: ubuntu
          port: 22
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          overwrite: true
          # Selecting all folders except "node_modules"
          source: "*"
          # The path is based on the directory where the user logged into the server starts
          target: "/var/www/"
        