name: Deploy
on: 
  push:
    branches: [ main ]
jobs:
  docker:
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
       uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: whoami